# This workflow is used as the base for the other workflows mean to be run on the main branch.
name: CI - base

on:
  workflow_call:
    inputs:
      test-category:
        description: 'Test category'
        required: false
        type: string
        default: 'fast'
      setup-javafx-headless:
        description: 'Setup JavaFX headless'
        required: false
        type: boolean
        default: false

permissions:
  checks: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: 8.5

      - name: Set up JavaFX deps
        if: ${{ inputs.setup-javafx-headless }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y libxxf86vm1 libgl1-mesa-glx

      - name: Set up Virtual Display (for Linux)
        if: runner.os == 'Linux' && ${{ inputs.setup-javafx-headless }}
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Gradle test
        run: |
          gradle compositeTask -PtaskName=test -Pcategory=${{ inputs.test-category }} --info --no-daemon -PrunningOnCIServer=true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true