# This workflow is used as the base for the other workflows mean to be run on the main branch.
name: CI - base

on:
  workflow_call:
    inputs:
      test-project:
        description: 'Test project'
        required: true
        type: string

permissions:
  checks: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: 8.5

      - name: Gradle test ${{ inputs.test-project }}
        run: cd ${{ inputs.test-project }} && gradle test --stacktrace --info --no-daemon -PrunningOnCIServer=true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true