name: CI - session-visualizer

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  build:
    uses: ihmcrobotics/simulation-construction-set-2/.github/workflows/gradleCI-base.yml@develop
    with:
      test-project: "scs2-session-visualizer"